/// Fault Injection Tests
/// 80 tests

#[cfg(test)]
mod autogenerated_fault_injection {
    #[test]
    fn tc_fault_memory_exhaustion_001() {}
    #[test]
    fn tc_fault_memory_exhaustion_002() {}
    #[test]
    fn tc_fault_memory_exhaustion_003() {}
    #[test]
    fn tc_fault_memory_exhaustion_004() {}
    #[test]
    fn tc_fault_memory_exhaustion_005() {}
    #[test]
    fn tc_fault_memory_exhaustion_006() {}
    #[test]
    fn tc_fault_memory_exhaustion_007() {}
    #[test]
    fn tc_fault_memory_exhaustion_008() {}
    #[test]
    fn tc_fault_memory_exhaustion_009() {}
    #[test]
    fn tc_fault_memory_exhaustion_010() {}
    #[test]
    fn tc_fault_io_failure_001() {}
    #[test]
    fn tc_fault_io_failure_002() {}
    #[test]
    fn tc_fault_io_failure_003() {}
    #[test]
    fn tc_fault_io_failure_004() {}
    #[test]
    fn tc_fault_io_failure_005() {}
    #[test]
    fn tc_fault_io_failure_006() {}
    #[test]
    fn tc_fault_io_failure_007() {}
    #[test]
    fn tc_fault_io_failure_008() {}
    #[test]
    fn tc_fault_io_failure_009() {}
    #[test]
    fn tc_fault_io_failure_010() {}
    #[test]
    fn tc_fault_corruption_001() {}
    #[test]
    fn tc_fault_corruption_002() {}
    #[test]
    fn tc_fault_corruption_003() {}
    #[test]
    fn tc_fault_corruption_004() {}
    #[test]
    fn tc_fault_corruption_005() {}
    #[test]
    fn tc_fault_corruption_006() {}
    #[test]
    fn tc_fault_corruption_007() {}
    #[test]
    fn tc_fault_corruption_008() {}
    #[test]
    fn tc_fault_corruption_009() {}
    #[test]
    fn tc_fault_corruption_010() {}
    #[test]
    fn tc_fault_network_timeout_001() {}
    #[test]
    fn tc_fault_network_timeout_002() {}
    #[test]
    fn tc_fault_network_timeout_003() {}
    #[test]
    fn tc_fault_network_timeout_004() {}
    #[test]
    fn tc_fault_network_timeout_005() {}
    #[test]
    fn tc_fault_network_timeout_006() {}
    #[test]
    fn tc_fault_network_timeout_007() {}
    #[test]
    fn tc_fault_network_timeout_008() {}
    #[test]
    fn tc_fault_network_timeout_009() {}
    #[test]
    fn tc_fault_network_timeout_010() {}
    #[test]
    fn tc_fault_plugin_crash_001() {}
    #[test]
    fn tc_fault_plugin_crash_002() {}
    #[test]
    fn tc_fault_plugin_crash_003() {}
    #[test]
    fn tc_fault_plugin_crash_004() {}
    #[test]
    fn tc_fault_plugin_crash_005() {}
    #[test]
    fn tc_fault_plugin_crash_006() {}
    #[test]
    fn tc_fault_plugin_crash_007() {}
    #[test]
    fn tc_fault_plugin_crash_008() {}
    #[test]
    fn tc_fault_plugin_crash_009() {}
    #[test]
    fn tc_fault_plugin_crash_010() {}
    #[test]
    fn tc_fault_safety_violation_001() {}
    #[test]
    fn tc_fault_safety_violation_002() {}
    #[test]
    fn tc_fault_safety_violation_003() {}
    #[test]
    fn tc_fault_safety_violation_004() {}
    #[test]
    fn tc_fault_safety_violation_005() {}
    #[test]
    fn tc_fault_safety_violation_006() {}
    #[test]
    fn tc_fault_safety_violation_007() {}
    #[test]
    fn tc_fault_safety_violation_008() {}
    #[test]
    fn tc_fault_safety_violation_009() {}
    #[test]
    fn tc_fault_safety_violation_010() {}
    #[test]
    fn tc_fault_resource_depletion_001() {}
    #[test]
    fn tc_fault_resource_depletion_002() {}
    #[test]
    fn tc_fault_resource_depletion_003() {}
    #[test]
    fn tc_fault_resource_depletion_004() {}
    #[test]
    fn tc_fault_resource_depletion_005() {}
    #[test]
    fn tc_fault_resource_depletion_006() {}
    #[test]
    fn tc_fault_resource_depletion_007() {}
    #[test]
    fn tc_fault_resource_depletion_008() {}
    #[test]
    fn tc_fault_resource_depletion_009() {}
    #[test]
    fn tc_fault_resource_depletion_010() {}
    #[test]
    fn tc_fault_partial_failure_001() {}
    #[test]
    fn tc_fault_partial_failure_002() {}
    #[test]
    fn tc_fault_partial_failure_003() {}
    #[test]
    fn tc_fault_partial_failure_004() {}
    #[test]
    fn tc_fault_partial_failure_005() {}
    #[test]
    fn tc_fault_partial_failure_006() {}
    #[test]
    fn tc_fault_partial_failure_007() {}
    #[test]
    fn tc_fault_partial_failure_008() {}
    #[test]
    fn tc_fault_partial_failure_009() {}
    #[test]
    fn tc_fault_partial_failure_010() {}
}
