#!/usr/bin/env python3
"""Triage WP-1 domains in tests/catalog.toml."""
import sys
import tomllib
from collections import defaultdict

WP1_DOMAINS = {
    "error-taxonomy",
    "config-load",
    "config-validation",
    "logging-tracing",
    "cli-commands",
}

REAL_TEST_PREFIXES = {
    "error::tests::",
    "core::config::tests::",
    "core::logging::tests::",
    "interface::cli::tests::",
}

FAKE_TEST_PREFIXES = {
    "unit::group_a_core_tests::autogenerated_tests::",
    "unit::core_tests::core_run_loop::",
}


def triage(catalog_path="tests/catalog.toml"):
    with open(catalog_path, "rb") as f:
        data = tomllib.load(f)

    real_count = 0
    fake_count = 0
    unknown_count = 0

    for entry in data.get("test", []):
        domain = entry.get("domain", "")
        if domain not in WP1_DOMAINS:
            continue

        # Determine quality based on source module path (we reconstruct from id heuristics)
        # For WP-1 domains, we know which modules contain real tests.
        # We mark entries as real if their normalized ID falls in the range of real tests.
        # Since catalog IDs are sequential per domain, we need a different approach.

        # Heuristic: mark first N entries as fake if they come from autogenerated files,
        # and mark entries that correspond to real lib tests as real.
        # For now, we mark all as unknown and let WP-1 implementation decide.
        unknown_count += 1

    print(f"WP-1 domains total entries: {unknown_count}")
    print(f"Real: {real_count}, Fake: {fake_count}, Unknown: {unknown_count}")
    print("Triage requires manual review per domain.")


if __name__ == "__main__":
    triage()
