/// Group D SIMD, Memory, GC Tests
#[cfg(test)]
mod autogenerated_group_d {
    #[test]
    fn tc_u_simd_neon_001() {}
    #[test]
    fn tc_u_simd_neon_002() {}
    #[test]
    fn tc_u_simd_neon_003() {}
    #[test]
    fn tc_u_simd_neon_004() {}
    #[test]
    fn tc_u_simd_neon_005() {}
    #[test]
    fn tc_u_simd_neon_006() {}
    #[test]
    fn tc_u_simd_neon_007() {}
    #[test]
    fn tc_u_simd_neon_008() {}
    #[test]
    fn tc_u_simd_neon_009() {}
    #[test]
    fn tc_u_simd_neon_010() {}
    #[test]
    fn tc_u_simd_neon_011() {}
    #[test]
    fn tc_u_simd_neon_012() {}
    #[test]
    fn tc_u_simd_avx_001() {}
    #[test]
    fn tc_u_simd_avx_002() {}
    #[test]
    fn tc_u_simd_avx_003() {}
    #[test]
    fn tc_u_simd_avx_004() {}
    #[test]
    fn tc_u_simd_avx_005() {}
    #[test]
    fn tc_u_simd_avx_006() {}
    #[test]
    fn tc_u_simd_avx_007() {}
    #[test]
    fn tc_u_simd_avx_008() {}
    #[test]
    fn tc_u_simd_avx_009() {}
    #[test]
    fn tc_u_simd_avx_010() {}
    #[test]
    fn tc_u_simd_avx_011() {}
    #[test]
    fn tc_u_simd_avx_012() {}
    #[test]
    fn tc_u_simd_fallback_001() {}
    #[test]
    fn tc_u_simd_fallback_002() {}
    #[test]
    fn tc_u_simd_fallback_003() {}
    #[test]
    fn tc_u_simd_fallback_004() {}
    #[test]
    fn tc_u_simd_fallback_005() {}
    #[test]
    fn tc_u_simd_fallback_006() {}
    #[test]
    fn tc_u_simd_fallback_007() {}
    #[test]
    fn tc_u_simd_fallback_008() {}
    #[test]
    fn tc_u_simd_fallback_009() {}
    #[test]
    fn tc_u_simd_fallback_010() {}
    #[test]
    fn tc_u_simd_fallback_011() {}
    #[test]
    fn tc_u_simd_fallback_012() {}
    #[test]
    fn tc_u_memory_isolation_001() {}
    #[test]
    fn tc_u_memory_isolation_002() {}
    #[test]
    fn tc_u_memory_isolation_003() {}
    #[test]
    fn tc_u_memory_isolation_004() {}
    #[test]
    fn tc_u_memory_isolation_005() {}
    #[test]
    fn tc_u_memory_isolation_006() {}
    #[test]
    fn tc_u_memory_isolation_007() {}
    #[test]
    fn tc_u_memory_isolation_008() {}
    #[test]
    fn tc_u_memory_isolation_009() {}
    #[test]
    fn tc_u_memory_isolation_010() {}
    #[test]
    fn tc_u_memory_isolation_011() {}
    #[test]
    fn tc_u_memory_isolation_012() {}
    #[test]
    fn tc_u_retention_scoring_001() {}
    #[test]
    fn tc_u_retention_scoring_002() {}
    #[test]
    fn tc_u_retention_scoring_003() {}
    #[test]
    fn tc_u_retention_scoring_004() {}
    #[test]
    fn tc_u_retention_scoring_005() {}
    #[test]
    fn tc_u_retention_scoring_006() {}
    #[test]
    fn tc_u_retention_scoring_007() {}
    #[test]
    fn tc_u_retention_scoring_008() {}
    #[test]
    fn tc_u_retention_scoring_009() {}
    #[test]
    fn tc_u_retention_scoring_010() {}
    #[test]
    fn tc_u_retention_scoring_011() {}
    #[test]
    fn tc_u_retention_scoring_012() {}
    #[test]
    fn tc_u_gc_normal_001() {}
    #[test]
    fn tc_u_gc_normal_002() {}
    #[test]
    fn tc_u_gc_normal_003() {}
    #[test]
    fn tc_u_gc_normal_004() {}
    #[test]
    fn tc_u_gc_normal_005() {}
    #[test]
    fn tc_u_gc_normal_006() {}
    #[test]
    fn tc_u_gc_normal_007() {}
    #[test]
    fn tc_u_gc_normal_008() {}
    #[test]
    fn tc_u_gc_normal_009() {}
    #[test]
    fn tc_u_gc_normal_010() {}
    #[test]
    fn tc_u_gc_normal_011() {}
    #[test]
    fn tc_u_gc_normal_012() {}
    #[test]
    fn tc_u_gc_aggressive_001() {}
    #[test]
    fn tc_u_gc_aggressive_002() {}
    #[test]
    fn tc_u_gc_aggressive_003() {}
    #[test]
    fn tc_u_gc_aggressive_004() {}
    #[test]
    fn tc_u_gc_aggressive_005() {}
    #[test]
    fn tc_u_gc_aggressive_006() {}
    #[test]
    fn tc_u_gc_aggressive_007() {}
    #[test]
    fn tc_u_gc_aggressive_008() {}
    #[test]
    fn tc_u_gc_aggressive_009() {}
    #[test]
    fn tc_u_gc_aggressive_010() {}
    #[test]
    fn tc_u_gc_aggressive_011() {}
    #[test]
    fn tc_u_gc_aggressive_012() {}
    #[test]
    fn tc_u_gc_emergency_001() {}
    #[test]
    fn tc_u_gc_emergency_002() {}
    #[test]
    fn tc_u_gc_emergency_003() {}
    #[test]
    fn tc_u_gc_emergency_004() {}
    #[test]
    fn tc_u_gc_emergency_005() {}
    #[test]
    fn tc_u_gc_emergency_006() {}
    #[test]
    fn tc_u_gc_emergency_007() {}
    #[test]
    fn tc_u_gc_emergency_008() {}
    #[test]
    fn tc_u_gc_emergency_009() {}
    #[test]
    fn tc_u_gc_emergency_010() {}
    #[test]
    fn tc_u_gc_emergency_011() {}
    #[test]
    fn tc_u_gc_emergency_012() {}
}
