/// Group C Block, Synapse, Sparse Tests
#[cfg(test)]
mod autogenerated_group_c {
    #[test]
    fn tc_u_block_sequence_001() {}
    #[test]
    fn tc_u_block_sequence_002() {}
    #[test]
    fn tc_u_block_sequence_003() {}
    #[test]
    fn tc_u_block_sequence_004() {}
    #[test]
    fn tc_u_block_sequence_005() {}
    #[test]
    fn tc_u_block_sequence_006() {}
    #[test]
    fn tc_u_block_sequence_007() {}
    #[test]
    fn tc_u_block_sequence_008() {}
    #[test]
    fn tc_u_block_sequence_009() {}
    #[test]
    fn tc_u_block_sequence_010() {}
    #[test]
    fn tc_u_block_sequence_011() {}
    #[test]
    fn tc_u_block_sequence_012() {}
    #[test]
    fn tc_u_block_prediction_001() {}
    #[test]
    fn tc_u_block_prediction_002() {}
    #[test]
    fn tc_u_block_prediction_003() {}
    #[test]
    fn tc_u_block_prediction_004() {}
    #[test]
    fn tc_u_block_prediction_005() {}
    #[test]
    fn tc_u_block_prediction_006() {}
    #[test]
    fn tc_u_block_prediction_007() {}
    #[test]
    fn tc_u_block_prediction_008() {}
    #[test]
    fn tc_u_block_prediction_009() {}
    #[test]
    fn tc_u_block_prediction_010() {}
    #[test]
    fn tc_u_block_prediction_011() {}
    #[test]
    fn tc_u_block_prediction_012() {}
    #[test]
    fn tc_u_synapse_create_001() {}
    #[test]
    fn tc_u_synapse_create_002() {}
    #[test]
    fn tc_u_synapse_create_003() {}
    #[test]
    fn tc_u_synapse_create_004() {}
    #[test]
    fn tc_u_synapse_create_005() {}
    #[test]
    fn tc_u_synapse_create_006() {}
    #[test]
    fn tc_u_synapse_create_007() {}
    #[test]
    fn tc_u_synapse_create_008() {}
    #[test]
    fn tc_u_synapse_create_009() {}
    #[test]
    fn tc_u_synapse_create_010() {}
    #[test]
    fn tc_u_synapse_create_011() {}
    #[test]
    fn tc_u_synapse_create_012() {}
    #[test]
    fn tc_u_synapse_validate_001() {}
    #[test]
    fn tc_u_synapse_validate_002() {}
    #[test]
    fn tc_u_synapse_validate_003() {}
    #[test]
    fn tc_u_synapse_validate_004() {}
    #[test]
    fn tc_u_synapse_validate_005() {}
    #[test]
    fn tc_u_synapse_validate_006() {}
    #[test]
    fn tc_u_synapse_validate_007() {}
    #[test]
    fn tc_u_synapse_validate_008() {}
    #[test]
    fn tc_u_synapse_validate_009() {}
    #[test]
    fn tc_u_synapse_validate_010() {}
    #[test]
    fn tc_u_synapse_validate_011() {}
    #[test]
    fn tc_u_synapse_validate_012() {}
    #[test]
    fn tc_u_synapse_update_001() {}
    #[test]
    fn tc_u_synapse_update_002() {}
    #[test]
    fn tc_u_synapse_update_003() {}
    #[test]
    fn tc_u_synapse_update_004() {}
    #[test]
    fn tc_u_synapse_update_005() {}
    #[test]
    fn tc_u_synapse_update_006() {}
    #[test]
    fn tc_u_synapse_update_007() {}
    #[test]
    fn tc_u_synapse_update_008() {}
    #[test]
    fn tc_u_synapse_update_009() {}
    #[test]
    fn tc_u_synapse_update_010() {}
    #[test]
    fn tc_u_synapse_update_011() {}
    #[test]
    fn tc_u_synapse_update_012() {}
    #[test]
    fn tc_u_synapse_decay_001() {}
    #[test]
    fn tc_u_synapse_decay_002() {}
    #[test]
    fn tc_u_synapse_decay_003() {}
    #[test]
    fn tc_u_synapse_decay_004() {}
    #[test]
    fn tc_u_synapse_decay_005() {}
    #[test]
    fn tc_u_synapse_decay_006() {}
    #[test]
    fn tc_u_synapse_decay_007() {}
    #[test]
    fn tc_u_synapse_decay_008() {}
    #[test]
    fn tc_u_synapse_decay_009() {}
    #[test]
    fn tc_u_synapse_decay_010() {}
    #[test]
    fn tc_u_synapse_decay_011() {}
    #[test]
    fn tc_u_synapse_decay_012() {}
    #[test]
    fn tc_u_synapse_prune_001() {}
    #[test]
    fn tc_u_synapse_prune_002() {}
    #[test]
    fn tc_u_synapse_prune_003() {}
    #[test]
    fn tc_u_synapse_prune_004() {}
    #[test]
    fn tc_u_synapse_prune_005() {}
    #[test]
    fn tc_u_synapse_prune_006() {}
    #[test]
    fn tc_u_synapse_prune_007() {}
    #[test]
    fn tc_u_synapse_prune_008() {}
    #[test]
    fn tc_u_synapse_prune_009() {}
    #[test]
    fn tc_u_synapse_prune_010() {}
    #[test]
    fn tc_u_synapse_prune_011() {}
    #[test]
    fn tc_u_synapse_prune_012() {}
    #[test]
    fn tc_u_sparse_traversal_001() {}
    #[test]
    fn tc_u_sparse_traversal_002() {}
    #[test]
    fn tc_u_sparse_traversal_003() {}
    #[test]
    fn tc_u_sparse_traversal_004() {}
    #[test]
    fn tc_u_sparse_traversal_005() {}
    #[test]
    fn tc_u_sparse_traversal_006() {}
    #[test]
    fn tc_u_sparse_traversal_007() {}
    #[test]
    fn tc_u_sparse_traversal_008() {}
    #[test]
    fn tc_u_sparse_traversal_009() {}
    #[test]
    fn tc_u_sparse_traversal_010() {}
    #[test]
    fn tc_u_sparse_traversal_011() {}
    #[test]
    fn tc_u_sparse_traversal_012() {}
    #[test]
    fn tc_u_soa_layout_001() {}
    #[test]
    fn tc_u_soa_layout_002() {}
    #[test]
    fn tc_u_soa_layout_003() {}
    #[test]
    fn tc_u_soa_layout_004() {}
    #[test]
    fn tc_u_soa_layout_005() {}
    #[test]
    fn tc_u_soa_layout_006() {}
    #[test]
    fn tc_u_soa_layout_007() {}
    #[test]
    fn tc_u_soa_layout_008() {}
    #[test]
    fn tc_u_soa_layout_009() {}
    #[test]
    fn tc_u_soa_layout_010() {}
    #[test]
    fn tc_u_soa_layout_011() {}
    #[test]
    fn tc_u_soa_layout_012() {}
    #[test]
    fn tc_u_scalar_kernels_001() {}
    #[test]
    fn tc_u_scalar_kernels_002() {}
    #[test]
    fn tc_u_scalar_kernels_003() {}
    #[test]
    fn tc_u_scalar_kernels_004() {}
    #[test]
    fn tc_u_scalar_kernels_005() {}
    #[test]
    fn tc_u_scalar_kernels_006() {}
    #[test]
    fn tc_u_scalar_kernels_007() {}
    #[test]
    fn tc_u_scalar_kernels_008() {}
    #[test]
    fn tc_u_scalar_kernels_009() {}
    #[test]
    fn tc_u_scalar_kernels_010() {}
    #[test]
    fn tc_u_scalar_kernels_011() {}
    #[test]
    fn tc_u_scalar_kernels_012() {}
}
